### ISSUE TITLE
Vehicle Despawn cmd doesnt work

### ISSUE THREAD

**Issue by PRownd11** [carsakiller/Carsas-CommandsV2#104]
### This is an issue with:

Vehicles (teleporting, despawning)

### How was the game being hosted?

It was a dedicated server

### Bug Priority

Major

### Issue Description

Simple. despawn command doesnt work.

### Reproduction Steps

1.Join
2. ?despawn
3. NO WORKY

**Comment by carsakiller** [comment]
This is due to the large API changes made by the Stormworks devs. See #103
