### ISSUE TITLE
Issues getting Companion working.

### ISSUE THREAD

**Issue by ThreeForths** [carsakiller/Carsas-CommandsV2#74]
Made a comment on the steam page before realizing you preferred questions and issues being posted here so here I am.

I can get Carsas Commands working on a local server WITHOUT the companion just fine. 

I go to multiplayer, create a new world, and choose Carsas Commands V2

Whenever I enable the Companion, my game simply crashes, or is so laggy I cannot move.

Here is a log hopefully to see what I am doing incorrectly. 

Do note that when I launch this server WITHOUT the companion enabled it launches fine and I can play using the ingame commands. 

[log.txt](https://github.com/carsakiller/Carsas-CommandsV2/files/8858166/log.txt)

**Comment by CrazyFluffyPony** [comment]
@ThreeForths thanks for the bug report. I downloaded a fresh copy of the companion server and used the latest Stormworks version and Carsa's Commands version. Then created a new multiplayer game with Carsas Commands V2 enabled. And it worked.

Can you please (and i hate that i have to say this) make sure you have the latest companion executable, the latest Stormworks version and the latest Carsas Commands version.
Then try again.

If it still does not work, try to start the server without the companion enabled and when loaded into the game open the chat and write

`?setPref companion true`

If the game crashes again, please send us your hardware specs and software specs.

**Comment by ThreeForths** [comment]
I'll double and triple check that everything is up to date tonight.

**Comment by carsakiller** [comment]
Seeing as there has been no updates in a while, I am going to close this issue.
