### ISSUE TITLE
C2 packetSendingQueue error when connecting carsas companion

### ISSUE THREAD

**Issue by Theshuffs** [carsakiller/Carsas-CommandsV2#75]
So when connecting Carsas companion website the chat gets flooded with this

![Screenshot 2022-08-17 144830](https://user-images.githubusercontent.com/102949456/185150973-946d4038-b23b-4c99-8bf1-551508396cb2.png)

and the logs are showing this 
![Screenshot 2022-08-17 145102](https://user-images.githubusercontent.com/102949456/185151389-c521b44b-293a-4d69-9ea2-40f8c9dcdcdd.png)

**Comment by carsakiller** [comment]
Thanks for reporting, we'll look into this!

**Comment by carsakiller** [comment]
This appears to be fixed by #78 however I was not able to replicate on the current version (`2.0.0`, [da3f0e3](https://github.com/carsakiller/Carsas-CommandsV2/commit/da3f0e33323f74d875af0350f6776f74cd99dca7)).
