### ISSUE TITLE
Issue in career

### ISSUE THREAD

**Issue by Theshuffs** [carsakiller/Carsas-CommandsV2#76]
### This is an issue with:

Other

### How was the game being hosted?

It was being hosted from the main menu

### Bug Priority

Critical

### Issue Description

The game chat is at first flooded with this when making a career server with carsas commands enabled

![image](https://user-images.githubusercontent.com/102949456/185153624-87d88374-32de-4f31-bea9-045f452b18cf.png)

Around 5 minutes after the world is created the warning changes to this
![image](https://user-images.githubusercontent.com/102949456/185153984-8c2141b0-3c4e-4e4e-8258-21211f9d58c1.png)

### Reproduction Steps

1.Make a friend-multiplayer career world (Not classic)
2.Have all official addons enabled (Including Weapons DLC)
3.Enable Carsas commands (version 2)
4. Click on Carsas commands and enable companion
5. Create the world and look at chat

**Comment by carsakiller** [comment]
Interesting, this may be a bug in Stormworks that results in `onVehicleSpawn()` getting called before `onCreate()`. Does this error happen if you are not using the weapons DLC addons?

**Comment by Theshuffs** [comment]
I haven't tried it without the dlc

**Comment by carsakiller** [comment]
I am able to reproduce, debugging...

**Comment by carsakiller** [comment]
Looks like my suspicions were correct, `onVehicleSpawn()` is getting called before `onCreate()`.

Please check if https://github.com/carsakiller/Carsas-CommandsV2/pull/78 fixes the issue. This can be done by taking the below zip and extracting it at `%APPDATA%\Stormworks\data\missions`. Then when starting a world, go to the `saved` tab in the `enabled addons` menu and proceed like normal.

[Carsa's Commands.zip](https://github.com/carsakiller/Carsas-CommandsV2/files/9412301/Carsa.s.Commands.zip)
