### ISSUE TITLE
Over time C2 starts spamming chat with warnings

### ISSUE THREAD

**Issue by Gamerboi12345** [carsakiller/Carsas-CommandsV2#79]
### This is an issue with:

Other

### How was the game being hosted?

It was being hosted from the main menu

### Bug Priority

Majior. It happens every time, and makes the companion completely useless,.

### Issue Description

After a while, C2 starts spamming the chat with "C2 packetSendingQueue is filling up (please contact a dev): 1636 most packet type: sync-SCRIPT_VERSION" it will vary the type to sync-rules, etc. Ocasionally it will also say "Companion server is not available"

### Reproduction Steps

1.Have companion enabled
2.Start game
3.Play game like normal (Spawn vehicles, etc) and wait for warnings to come in

**Comment by carsakiller** [comment]
Hello 👋

When this happens, is the companion connected to the game or has it failed to connect? It could be possible that the game is attempting to talk to the server, which isn't there. Could you please confirm if the companion is connected and receiving updates from the game?

**Comment by carsakiller** [comment]
So long as the server has been installed correctly and a connection to the game has been established, this problem should no longer persist as of `v2.0.3`. Closing as there has been no response and it should be resolved.
