### ISSUE TITLE
`?setPref startEquipmentA 0` returns "0 is not a valid equipment ID"

### ISSUE THREAD

**Issue by Drift91** [carsakiller/Carsas-CommandsV2#80]
### This is an issue with:

Preferences

### How was the game being hosted?

It was being hosted from the main menu

### Bug Priority

Medium priority, setting can be changed via save editing and isn't entirely game breaking.

### Issue Description

When trying to remove items from the starting equipment it appears to be impossible, as a value of `0` returns an error. I've also tried `none` but that returned an error yet again.

### Reproduction Steps

1. Load into game with addon enabled.
2. Enter in chat `?setPref startEquipmentA 0`

**Comment by carsakiller** [comment]
Should be fixed in this next version, thanks!

**Comment by Drift91** [comment]
Yep, seems to be working. Thank you.
