### ISSUE TITLE
Cant find script folder for dedicated server

### ISSUE THREAD

**Issue by Smetana5** [carsakiller/Carsas-CommandsV2#84]
### This is an issue with:

Other

### How was the game being hosted?

It was a dedicated server

### Bug Priority

Cant install carsas Commands

### Issue Description

I just tried following the manual for installing on dedicated server but actually I cant find any folder at my %appdata%/Stormworks/Missions (Theres no missions folder)
I would love to install this mod to my server. Thank you,

### Reproduction Steps

1.Installed and turned mod in singlplayer. (from workshop)
2.Went into %appdata%/roaming/stormworks but theres no sign of carsas commands
3.Cant copy into server folder (I bought especially VPS for this, so I can run companion there and acces from anywhere, but I cant install it :D ) Its just fun project for friend, but I would love to finish it ;)

**Comment by CrazyFluffyPony** [comment]
@Smetana5 the folder is `%appdata%\Stormworks\data\missions`

**Comment by CrazyFluffyPony** [comment]
it should look like this
![image](https://user-images.githubusercontent.com/80415579/198901039-7b1549a6-f551-43f2-88d3-aef8099b85db.png)

**Comment by carsakiller** [comment]
@Smetana5 has your issue been resolved?
