### ISSUE TITLE
C2 packetSendingQueue is filling up (please contact a dev): 1000 (counts up) most packet type: stream-map

### ISSUE THREAD

**Issue by TheRealHomeland** [carsakiller/Carsas-CommandsV2#88]
### This is an issue with:

Other

### How was the game being hosted?

It was a dedicated server

### Bug Priority

Minor(ish); seems to be lowering TPS by 10pts

### Issue Description

On fresh install (following guide), it seems like admins are getting pinged with 

"C2 packetSendingQueue is filling up (please contact a dev): 1000 (counts up) most packet type: stream-map"

It also seems to be impacting TPS by 10ish points (goes between 47-50 TPS randomly). I've disabled all other missions except a small selection of default ones and deleted the savegame. When I disable Carsa's Commands and restart, TPS goes back up 

### Reproduction Steps

1. Fresh install of Carsa's Commands
2. Update owner info
3. Delete savegane
4. Relaunch server

### Additional Info

Server is hosted through GTX

**Comment by carsakiller** [comment]
Could you list the other enabled addons? If they are spawning lots of vehicles, they could be causing the slow-down as the server streams the data to the companion app.

**Comment by TheRealHomeland** [comment]
`<path path="rom/data/missions/Carsa's Commands"/>
		<path path="rom/data/missions/vehicleLimit"/>
		<path path="rom/data/missions/resource_trading_enhanced"/>
		<path path="rom/data/missions/EasyServerCustomisation"/>
		<path path="rom/data/missions/default_dock_bollards"/>
		<path path="rom/data/missions/default_elevators"/>
		<path path="rom/data/missions/default_resource_storage"/>
		<path path="rom/data/missions/default_mission_locations"/>
		<path path="rom/data/missions/default_mission_transport_locations"/>
		<path path="rom/data/missions/default_mission_zones_building"/>
		<path path="rom/data/missions/default_mission_zones_delivery"/>
		<path path="rom/data/missions/default_mission_zones_main"/>
		<path path="rom/data/missions/default_mission_zones_sawyer"/>
		<path path="rom/data/missions/default_paths"/>
		<path path="rom/data/missions/default_resource_trading"/>
		<path path="rom/data/missions/dlc_weapons_ai"/>
		<path path="rom/data/missions/default_mission_zones_arid"/>
		<path path="rom/data/missions/default_railroad_signals"/>
		<path path="rom/data/missions/default_landmarks"/>`

It's a SAR/missions server so a lot of the mission-generating missions have remained. I've gone inside the addons to lower the AI spawn count down to like <50 from 148 or something

**Comment by TheRealHomeland** [comment]
Companion module looks disabled as well, not currently planning on using the webhook. Would it be smarted to default back to v1 where it didn't have to send data?

**Comment by carsakiller** [comment]
Hmm, running [`?preferences`](https://c2.carsakiller.com/cc-website/docs/commands#preferences) should tell you if the companion is disabled. [`?setPref`](https://c2.carsakiller.com/cc-website/docs/commands#setPref) will disable it, if it is not already:
`?setPref companion false`.

I would not recommend going back to `v1` as it is using the severely outdated API and is no longer receiving support.

**Comment by TheRealHomeland** [comment]
> Hmm, running [`?preferences`](https://c2.carsakiller.com/cc-website/docs/commands#preferences) should tell you if the companion is disabled. [`?setPref`](https://c2.carsakiller.com/cc-website/docs/commands#setPref) will disable it, if it is not already: `?setPref companion false`.
> 
> I would not recommend going back to `v1` as it is using the severely outdated API and is no longer receiving support.

Guess I didn't disable it- thank you again for the help, much appreciated haha. TPS is back up and stable! Amazing support

**Comment by carsakiller** [comment]
Going to re-open this so that we can further investigate the TPS slowdown and queue filling.

**Comment by CrazyFluffyPony** [comment]
@TheRealHomeland out of curiosity we would like you to test something for us. Then we could fix the actual "bug" for others too.

Edit Line 5889 in the file `%appdata%\Stormworks\data\missions\Carsa's Commands\script.lua`

and make it say:

```lua
local LIVESTREAM_TIME_BETWEEN = 60 * 20
```

If the error message disappears, we know what is wrong

**Comment by TheRealHomeland** [comment]
Changed the line to reflect "20" instead of "2" and tried with "setPref companion false" and "setPref companion true", no slowdown on either!

**Comment by CrazyFluffyPony** [comment]
@TheRealHomeland thanks a lot! That helps

**Comment by CrazyFluffyPony** [comment]
@CrazyFluffyPony the `ignoreServerNotAvailable` parameter in `sendToServer()` allows the `stream-map` to be added to queue, when the server is not connected.

This behaviour is wrong.
Instead, for `stream-map` etc. we should do the following: if server not available, drop the message and do not add it to queue

**Comment by CrazyFluffyPony** [comment]
@TheRealHomeland we published an update for Carsas Commands and the companion which address the issue.
