### ISSUE TITLE
New stormworks update - required carsas commands update for the /give command

### ISSUE THREAD

**Issue by Theshuffs** [carsakiller/Carsas-CommandsV2#94]
The /give command has been glitching out since the new update with the expanded inventory update 
![image](https://user-images.githubusercontent.com/102949456/206787464-3e745153-dcfe-437a-b757-172bd66f3f74.png)

**Comment by carsakiller** [comment]
Have the devs changed which items are considered small? I have already fixed the slots problem but it appears that ammo is no longer a small item... or was it always a large item?

**Comment by Theshuffs** [comment]
I'm not sure what the devs have done regarding the items

**Comment by carsakiller** [comment]
v1 is very outdated and is no longer receiving updates. There is far too much to fix in it now. It is licensed under MIT, though, so you are free to make any changes to it. You may be able to edit a table or function to define the new slots.

**Comment by Theshuffs** [comment]
> v1 is very outdated and is no longer receiving updates. There is far too much to fix in it now. It is licensed under MIT, though, so you are free to make any changes to it. You may be able to edit a table or function to define the new slots.

How/where can i edit the version 1?

**Comment by Theshuffs** [comment]
![image](https://user-images.githubusercontent.com/102949456/207945070-732710a7-22bd-4268-915e-309db2366037.png)
I have explored the code and added to the code and it's now working! 
Can i post this to the workshop to personally maintain it for me and my friends?

**Comment by Theshuffs** [comment]
I have also added a line to give the player a glowstick

**Comment by Theshuffs** [comment]
If i can publish it, how do you upload an addon like this?

**Comment by carsakiller** [comment]
> Can i post this to the workshop to personally maintain it for me and my friends?

Yes

> If i can publish it, how do you upload an addon like this?

It is done in-game using the addon editor. You click the save button and select "Workshop"

**Comment by carsakiller** [comment]
Fixed in [`v2.1.2`](https://github.com/carsakiller/Carsas-CommandsV2/releases/tag/v2.1.2)
